### ISSUE TITLE
[FEATURE] 개발 환경설정

### ISSUE THREAD

**Issue by CokeLee777** [swyg-goorm/inferring_server#1]
## Description

각 프로파일에 따른 환경설정

## To-do
- [x] 개발, 프로덕션 환경 분리 및 설정
- [x] 개발, 프로덕션 환경에 따른 Dockerfile 분리해서 작성
- [x] CI/CD 파이프라인 구성
